#!/bin/bash
# -*- mode: sh -*-
# © Copyright IBM Corporation 2015.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

INSTALL_DIR=/opt/mqlight
CACHE_FILE=/var/cache/mqlight-data.tar.gz
export PATH=$PATH:$INSTALL_DIR:$INSTALL_DIR/runtime/bin
CONFIG=""

config()
{
	if [ -n "$MQLIGHT_USER" ]; then
		CONFIG="$CONFIG --user $MQLIGHT_USER"
	fi
	if [ -n "$MQLIGHT_PASSWORD" ]; then
		CONFIG="$CONFIG --password $MQLIGHT_PASSWORD"
	fi
	if [ -n "$MQLIGHT_TLS_PASSPHRASE" ]; then
		CONFIG="$CONFIG --ssl-passphrase $MQLIGHT_TLS_PASSPHRASE"
	fi
	if [ -n "$MQLIGHT_TLS_KEYSTORE" ]; then
		CONFIG="$CONFIG --ssl-keystore $MQLIGHT_TLS_KEYSTORE"
	fi
}

initialize()
{
	set -x
	export AMQ_INHIBIT_O_DIRECT=TRUE
	mqlight-config -v
	mqlight-config --accept-license
	mqlight-start --no-browser
	mqlight-stop
	rm -rf $MQLIGHT_DATA_PATH/mqm/.lapc
	GZIP=-9 tar zcf $CACHE_FILE -C $MQLIGHT_DATA_PATH .
	rm -rf $MQLIGHT_DATA_PATH
	mkdir $MQLIGHT_DATA_PATH
}

licenseCheck()
{
	if [ "$LICENSE" = "accept" ]; then
		CONFIG="$CONFIG --accept-license"
		return
	elif [ "$LICENSE" = "view" ]; then
		mqlight-config --show-license
		exit 1
	else
		echo -e "Set environment variable LICENSE=accept to indicate acceptance of license terms and conditions.\n\nLicense agreements and information can be viewed by running this image with the environment variable LICENSE=view."
		exit 2
	fi
}

monitor()
{
	echo "----------------------------------------"
	echo "Monitoring MQ Light..."

	# Loop until "dspmq" says the queue manager is running
	until [ "`dspmq -n | cut -f3 -d"("`" == "RUNNING)" ]; do
		sleep 1
	done
	dspmq

	# Loop until "dspmq" says the queue manager is not running any more
	until [ "`dspmq -n | cut -f3 -d"("`" != "RUNNING)" ]; do
		sleep 5
	done
	dspmq
}

runmqras()
{
	echo "$INSTALL_DIR/runtime/bin/runmqras -section all -outputdir $MQLIGHT_DATA_PATH/mqm/errors"
	$INSTALL_DIR/runtime/bin/runmqras -section all -outputdir $MQLIGHT_DATA_PATH/mqm/errors
}

start()
{
	if [ ! -f $MQLIGHT_DATA_PATH/mqm/mqs.ini ]; then
		if [ -n "$MQLIGHT_REGENERATE_DATA" ]; then
			echo "Reinitializing IBM MQ Light"
		else
			echo "Initializing IBM MQ Light"
			tar zxf $CACHE_FILE -C $MQLIGHT_DATA_PATH
                fi
	fi
	( set -x ; mqlight-config -v ; mqlight-config $CONFIG ;	mqlight-start --no-browser )
}

stop()
{
	mqlight-stop
	dspmq
	exit
}

case "$1" in
	initialize)	initialize;;
	runmqras)	runmqras;;
	stop)		stop;;
	start|*)	licenseCheck
			config
			start
			trap stop SIGTERM SIGINT
			monitor
			;;
esac
